name: polyglot
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+25

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.10
  desktop_window: ^0.4.0
  flutter_riverpod: ^2.0.0-dev.9
  file_picker: ^4.6.1
  pluto_grid: ^4.0.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons_maker: ^0.10.2

flutter:
  uses-material-design: true
  assets:
    - internalization_languages.json
    - logo.png

flutter_icons:
  macos: true
  windows: true
  image_path: "assets/logo.png"